# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-21 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0002_auto_20190220_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='-', null=True),
        ),
    ]
